name: adapcard
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.5.0=h27087fc_0
  - blas=2.16=mkl
  - brotli-python=1.0.9=py37hd23a5d3_7
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=h35add3b_1015
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.4.127=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - cudatoolkit=11.6.2=hfc3e2af_13
  - dav1d=1.2.1=hd590300_0
  - ffmpeg=6.0.0=gpl_hdbbbd96_103
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h48d6fc4_0
  - fribidi=1.0.10=h36c2ea0_0
  - gds-tools=1.9.1.3=0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - harfbuzz=7.3.0=hdb3a94d_0
  - icu=72.1=hcb278e6_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.23.1=h8e693c7_0
  - libass=0.17.1=hc9aadba_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.84.0=h2ff4ddf_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libopus=1.4=hd0c01bc_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.4.0=h82bc61c_5
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.11.5=h0d562d8_0
  - libzlib=1.3.1=hb9d3cd8_2
  - mkl=2020.2=256
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - nsight-compute=2024.1.1.4=0
  - numpy=1.21.6=py37h976b520_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.5.0=h7b32b05_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.44=hba22ea6_2
  - pip=22.3.1=py37h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - pytorch=1.13.0=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - svt-av1=1.6.0=h59595ed_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=0.13.0=py37_cu116
  - torchvision=0.14.0=py37_cu116
  - typing_extensions=4.7.1=pyha770c72_0
  - wheel=0.38.4=py37h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - arff==0.9
      - asn1crypto==0.24.0
      - atomicwrites==1.3.0
      - attrs==19.1.0
      - blessed==1.21.0
      - bloom-filter==1.3
      - brokenaxes==0.5.0
      - category-encoders==1.2.3
      - certifi==2019.3.9
      - cffi==1.12.3
      - chardet==3.0.4
      - cloudpickle==1.2.1
      - colorama==0.4.1
      - cryptography==42.0.8
      - cycler==0.10.0
      - dask==1.2.0
      - dataclasses==0.6
      - decorator==4.4.0
      - ete3==3.1.1
      - fonttools==4.38.0
      - gpustat==1.1.1
      - h5py==3.8.0
      - higher==0.2.1
      - idna==2.6
      - importlib-resources==5.12.0
      - jeepney==0.8.0
      - jinja2==3.1.6
      - joblib==0.13.2
      - keyring==10.6.0
      - keyrings-alt==3.0
      - kiwisolver==1.1.0
      - lark-parser==0.7.1
      - locket==0.2.0
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - mock==3.0.4
      - more-itertools==7.0.0
      - mpmath==1.1.0
      - networkx==2.6.3
      - numexpr==2.6.9
      - nvidia-ml-py==12.575.51
      - ordered-set==4.1.0
      - packaging==24.0
      - pandas==0.25.3
      - partd==1.0.0
      - patsy==0.5.1
      - pillow==9.5.0
      - pluggy==0.9.0
      - psutil==7.0.0
      - psycopg2==2.8.3
      - py==1.8.0
      - py4j==0.10.8.1
      - pybind11==2.3.0
      - pycparser==2.19
      - pycrypto==2.6.1
      - pydot==1.4.1
      - pyparsing==2.4.0
      - pyqt5==5.12.1
      - pyqt5-sip==4.19.15
      - pytest==4.4.1
      - python-dateutil==2.7.5
      - pytz==2018.7
      - pyverdict==0.1.3.2
      - pyxdg==0.25
      - pyyaml==3.12
      - requests==2.18.4
      - scikit-learn==1.0.2
      - scipy==1.2.1
      - seaborn==0.12.2
      - secretstorage==2.3.1
      - six==1.12.0
      - sklearn==0.0
      - spflow==0.0.41
      - sqlalchemy==1.3.11
      - sqlparse==0.3.0
      - statsmodels==0.9.0
      - sympy==1.4
      - tables==3.5.1
      - threadpoolctl==3.1.0
      - toolz==0.9.0
      - torch-geometric==2.3.1
      - tqdm==4.31.1
      - urllib3==1.22
      - var-dump==1.2
      - wcwidth==0.2.13
      - wincertstore==0.2
      - zipp==3.15.0
prefix: /home/dafn/anaconda3/envs/deepcard
